server:
  port: 9001
spring:
  application:
    name: spring_cloud_zuul_9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance: 
    # 监控显示id
    instance-id: zuul9001.com
    # 是否隐藏真实ip
    prefer-ip-address: true
zuul:
  # 映射请求
  routes:
    demo.serviceId: demo
    demo.path: /d/**
  # 忽略请求
  ignored-services: demo

