server:
  port: 7001
#Eureka配置
eureka:
  instance:
    #Eureka服务端的实例名称
    hostname: eureka-server1
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: false
    #false代表自己是注册中心
    # fetch-registry: false
    #注册地址,监控是http://${eureka.instance.hostname}:${server.port}
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server2:7002/eureka/
      