server:
  port: 10001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ButchQiuQiu/spring_cloud_demo.git
          # 公开仓库可以不填账号密码
        # username:
        # password: 
          # 配置文件分支
          default-label: master 
          # 配置文件所在根目录
          search-paths: config
eureka:
  client:
    service-url:
      #服务注册地址,对应eureka的服务注册url
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/  
