server:
  port: 80

spring:
  datasource:
    username: root
    password: 199598
    url: jdbc:mysql://localhost:3306/greenbirdoa?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    # 不向eureka注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server2:7002/eureka/,http://eureka-server1:7001/eureka/

# 开启服务降级
feign:
  hystrix:
    enabled: true


