server:
  port: 8001

spring:
  application:
    name: demo
  datasource:
    username: root
    password: 199598
    url: jdbc:mysql://localhost:3306/greenbirdoa?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    
eureka:
  client:
    service-url:
      #服务注册地址,对应eureka的服务注册url
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

