server:
  port: 7888
spring:
  cloud:
    stream:
      default-binder: kafka #默认的绑定器，
      kafka: #如果用的是rabbitMQ这里填 rabbit
        binder:
          brokers: #Kafka的消息中间件服务器地址
          - localhost:9092
      bindings:
        output: #通道名称(org.springframework.cloud.stream.messaging.Source绑定也可以自定义需要自定义Source类)
          binder: kafka
          destination: test1 #消息发往的目的地，对应topic
          group: output-group-1 #对应kafka的group
          content-type: text/plain #消息的格式
        my-out:  # 自定义管道
          binder: kafka
          destination: myset # 消息发送低，对应topic主题
          group: output-group-2 # 对应kafka的group
          content-type: text/plain # 消息格式
          
          